# Generated by Django 5.0.7 on 2024-10-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior_house', '0003_contact_form_userregistration_form_delete_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Form',
            new_name='ContactForm',
        ),
        migrations.RenameModel(
            old_name='UserRegistration_Form',
            new_name='UserRegistration',
        ),
    ]
