# Generated by Django 5.0.7 on 2024-11-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior_house', '0004_rename_contact_form_contactform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='project',
            new_name='describe_project',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='location',
            new_name='project_location',
        ),
    ]
